/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Managing;
import controller.ManagingFactory;

/**
 *
 * @author anime
 */
public class MAIN extends javax.swing.JFrame {
    ManagingFactory mf = new ManagingFactory();
    Managing managing = mf.getManaging("User");
    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        findbook = new javax.swing.JButton();
        RentalBook = new javax.swing.JButton();
        ReturnBook = new javax.swing.JButton();
        ModifyInformation = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel1.setText("메인 화면");

        findbook.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        findbook.setText("도서검색");
        findbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbookActionPerformed(evt);
            }
        });

        RentalBook.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        RentalBook.setText("도서대출");
        RentalBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentalBookActionPerformed(evt);
            }
        });

        ReturnBook.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        ReturnBook.setText("도서반납");
        ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookActionPerformed(evt);
            }
        });

        ModifyInformation.setFont(new java.awt.Font("굴림", 0, 14)); // NOI18N
        ModifyInformation.setText("정보수정");
        ModifyInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyInformationActionPerformed(evt);
            }
        });

        logout.setText("로그아웃");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModifyInformation)
                    .addComponent(ReturnBook)
                    .addComponent(RentalBook)
                    .addComponent(findbook))
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logout))
                .addGap(18, 18, 18)
                .addComponent(findbook)
                .addGap(18, 18, 18)
                .addComponent(RentalBook)
                .addGap(18, 18, 18)
                .addComponent(ReturnBook)
                .addGap(18, 18, 18)
                .addComponent(ModifyInformation)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbookActionPerformed
        SEARCHBOOK search = new SEARCHBOOK();
        search.setVisible(true);
        dispose();
    }//GEN-LAST:event_findbookActionPerformed

    private void RentalBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentalBookActionPerformed
        // TODO add your handling code here:
        Rental rental = new Rental();
        rental.setVisible(true);
        dispose();
    }//GEN-LAST:event_RentalBookActionPerformed

    private void ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookActionPerformed
        // TODO add your handling code here:
        Return_Book return_book = new Return_Book();
        return_book.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnBookActionPerformed

    private void ModifyInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyInformationActionPerformed
        EDITINFORMATION e = new EDITINFORMATION();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModifyInformationActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        LOGIN log = new LOGIN();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ModifyInformation;
    private javax.swing.JButton RentalBook;
    private javax.swing.JButton ReturnBook;
    private javax.swing.JButton findbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
